worldName: world-name
serverName: server-name
password: password
serverPublic: false

resources: {}

replicas: 1

storage:
  kind: persistentVolumeClaim
  hostvol:
    path: /data/valheim
  pvc:
    size: 1Gi

networking:
  serviceType: NodePort

nodeSelector: {}
